// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSci1JBiIn4BMhEZa8Ai5coyS88FKZWM',
    appId: '1:445349492178:web:50bdb4f0709e220a38440b',
    messagingSenderId: '445349492178',
    projectId: 'umkm-mart-717bc',
    authDomain: 'umkm-mart-717bc.firebaseapp.com',
    storageBucket: 'umkm-mart-717bc.firebasestorage.app',
    measurementId: 'G-76P35F6ZFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE2iduy9BimNypNRpDnAT9yvLteKAUlk8',
    appId: '1:445349492178:android:2e1186e409ee091a38440b',
    messagingSenderId: '445349492178',
    projectId: 'umkm-mart-717bc',
    storageBucket: 'umkm-mart-717bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORr_l3QeHIGXz8UYn729fDqBOwNEjNzQ',
    appId: '1:445349492178:ios:fc1b6bfcb994202138440b',
    messagingSenderId: '445349492178',
    projectId: 'umkm-mart-717bc',
    storageBucket: 'umkm-mart-717bc.firebasestorage.app',
    iosBundleId: 'com.example.umkmMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORr_l3QeHIGXz8UYn729fDqBOwNEjNzQ',
    appId: '1:445349492178:ios:fc1b6bfcb994202138440b',
    messagingSenderId: '445349492178',
    projectId: 'umkm-mart-717bc',
    storageBucket: 'umkm-mart-717bc.firebasestorage.app',
    iosBundleId: 'com.example.umkmMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfSci1JBiIn4BMhEZa8Ai5coyS88FKZWM',
    appId: '1:445349492178:web:eaf4585deb17c4e038440b',
    messagingSenderId: '445349492178',
    projectId: 'umkm-mart-717bc',
    authDomain: 'umkm-mart-717bc.firebaseapp.com',
    storageBucket: 'umkm-mart-717bc.firebasestorage.app',
    measurementId: 'G-T7L3ZTXEZ2',
  );
}
